### ISSUE TITLE
How to use bigdecimalmath on Delphi 10.1 Berlin, I am a newbie of delphi.

### ISSUE THREAD

**Issue by tuan-ha** [benibela/bigdecimalmath#1]
When use bigdecimalmath on Berlin, I have alot error
[dcc32 Error] bigdecimalmath.pas(36): E1030 Invalid compiler directive: 'mode'
[dcc32 Error] bigdecimalmath.pas(149): E2029 '=' expected but ':=' found
[dcc32 Error] bigdecimalmath.pas(149): E2029 '=' expected but ')' found
...

**Comment by benibela** [comment]
You cannot.

It is for freepascal only. I do not have a recent Delphi version
